CBICA Toolkit: DicomIOManager< T > Class Template Reference
DicomIOManager< T > Class Template Reference
Public Types
typedef std::vector< std::string > FileNamesContainer
typedef itk::GDCMImageIO ImageIOType
typedef itk::GDCMSeriesFileNames NamesGeneratorType
Public Member Functions
template<class TInputImage >
T::Pointer ConvertImage3DToFloatImage3D (typename TInputImage::Pointer image)
helper to write itk image
T::Pointer GetITKImage ()
get the read dicom data as 3D float ITK image
bool LoadDicom ()
load dicom data
void SetDirectoryPath (std::string path)
set the input directory containing dicom series
Static Public Member Functions
static bool CanReadFile (std::string path, itk::ImageIOBase::Pointer &imageIO)
check if file can be read or not and return the base imageIO if readable
static bool IsDicom (std::string path)
check if file is dicom
Member Function Documentation
ConvertImage3DToFloatImage3D()
T::Pointer ConvertImage3DToFloatImage3D (typename TInputImage::Pointer image)
helper to write itk image
convert itk image to float 3D itk image
LoadDicom()
bool LoadDicom ()
load dicom data
no files in the given directory
get the first file in the given directory and check its pixel type and component type so we can invoke the load with appropriate template type
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
need this type of data this needs to be handled when we get the data
References DicomImageReader::ReadDicomImage(), DicomSeriesReader::ReadDicomSeries(), and DicomSeriesReader::SetDirectoryPath().
Referenced by cbica::ReadImage().
The documentation for this class was generated from the following files:
src/classes/itk/IO/inc/DicomIOManager.h
src/classes/itk/IO/inc/DicomIOManager.hxx